### ISSUE TITLE
Chatbox becomes movable sometimes after logging out then logging back in

### ISSUE THREAD

**Issue by supersaiyoon** [Xruptor/XanChat#1]
Sometimes when I log into toons, the chatbox will be unlocked/movable.  Even though I lock the position (I always keep it locked from moving), they become unlocked when I exit the game or log out then back in.  It's random when it happens, and I always properly log out or exit the game.

Feel free to contact me if you need anymore info.  Thanks again for this wonderful add-on and keeping it up to date :)

**Comment by supersaiyoon** [comment]
Note: I also noticed that it unlocks whenever I disable/enable an add-on while in game and use the "Reload UI" button afterward.

**Comment by Xruptor** [comment]
Alright! So lets get started.... First off have you tried disabling all addons and just keep xanChat loaded.  Does the issue still persist when only xanChat is loaded.  Does typing /reload or /reloadui still cause the frames to move around or unlock?  When you say they are movable you mean that you can actually drag them without much of an issue or that you've accidentally moved them?  I looked at the code and have not see a place where it would plausibly cause it to unlock all the frames.  I believe there is a simple solution to this but I want to make sure it's xanChat that is causing the problem first.  :D

**Comment by supersaiyoon** [comment]
**1. Tried disabling addons and keep xanChat loaded?**

I tried it just now.  After logging onto a toon, I disabled all my addons except xanChat through the addon menu then clicked "Reload UI."  Chat window was still locked/unmovable.  However, after typing in /reload just to be sure, the chat window became unlocked, even when xanChat is the only addon enabled.

**2. When you say they are movable you mean that you can actually drag them without much of an issue or that you've accidentally moved them?**

Sorry, movable means when chatbox is unlocked (right-click General tab --> Lock/Unlock).

I'm not sure if this helps, but I did pretty much turned on all of your settings except text shadows.  Let me know if you need anymore info/screenshots.  Thanks again for looking into this.

**Comment by Xruptor** [comment]
Thanks for the very descriptive feedback.  Since it is indeed still happening with xanChat being the only thing loaded I can only conclude that the reload is causing the chatframes to reset their locked status.  I believe the simplest solution would be to force lock all the frames after a reload.  I'll see if I can whip something up and you can test it out.

**Comment by Xruptor** [comment]
Okay try this experimental version and tell me if you still get the weird unlock bug with your frames.  It should work even if you do a /reloadui 

Basically I'm forcing all the chat windows to lock regardless of settings.  I don't know of anyone that has movable chat frames constantly anyways.  

[xanChat.zip](https://github.com/Xruptor/XanChat/files/575459/xanChat.zip)

**Comment by supersaiyoon** [comment]
It seems to work so far after logging into multiple toons and doing /reload while disabling/re-enabling addons.  Thanks for the fix :D

**Comment by Xruptor** [comment]
Alright thanks I'll go ahead and push this as a live update then to WOWInterface and Curse.
