### ISSUE TITLE
Copy Button

### ISSUE THREAD

**Issue by Natlyz** [Xruptor/XanChat#11]
Hello!

Thanks for adding the copy feature. 

I like it the way it is already and I like the copy icon you made, but I have a suggestion you might like: the Copy Button.

![WoWScrnShot_030120_010827](https://user-images.githubusercontent.com/60573947/75617261-c56c6680-5b6d-11ea-8e52-e124ab6cba7a.png)

Thanks :)

**Comment by Xruptor** [comment]
I would love to put it there, but it would be more of a hassle than it's worth.  The location of the button in your picture actually does have additional buttons depending on what localization of WOW a person is playing.  In addition, Custom UI's wouldn't have that bar so the button would stick out on the side.  I could possibly add an option to move it but it would be a dirty switch.  Meaning it would move the button regardless if it's on top of anything.  I'll give it some thought and test it out, but I cannot promise I'll implement this.

**Comment by Natlyz** [comment]
It's just a suggestion. If it's hard to implement the copy feature is already nice the way it is.

**Comment by Xruptor** [comment]
> It's just a suggestion. If it's hard to implement the copy feature is already nice the way it is.

I added the feature.  I figured that if it interferes with another localization language, they can just turn it off and use it the default way.

**Comment by Natlyz** [comment]
Thanks! You implement new features so fast I feel a bit awkward asking for new ones now.
