### ISSUE TITLE
XanChat background

### ISSUE THREAD

**Issue by snarfaul** [Xruptor/XanChat#12]
I am not sure what happen to the XanChat Background.  I had it set to darker color but it give me lighter color each time after I relog.
This is really annoying.   
Please help., thanks

**Comment by Xruptor** [comment]
Have you had this issue before in previous versions of xanchat or did you start using it now?

**Comment by snarfaul** [comment]
I am new to XanChat, and I believe it happen since v7.1.

**Comment by Xruptor** [comment]
Can you provide me some screenshots?  Also can you attach your xanChat.lua from your WOW install directory.

Example:  C:\Games\World of Warcraft\_retail_\WTF\Account\YOUR ACCOUNT\SavedVariables\xanChat.lua

**Comment by snarfaul** [comment]
I attached 2 screenshots and 1 lua file. 
Let me know if you dont see it.

[XanChat_lua.txt](https://github.com/Xruptor/XanChat/files/4308034/XanChat_lua.txt)
![XanChat_Dark](https://user-images.githubusercontent.com/30013979/76239344-678bee80-61ff-11ea-9eac-b97b5b36d016.PNG)
![XanChat_light](https://user-images.githubusercontent.com/30013979/76239350-6a86df00-61ff-11ea-922d-ee7998d6c58a.PNG)

**Comment by Xruptor** [comment]
That's perfect!  Thanks!  It helps me figure out what's going on.  So I'm going to assume the top picture is how you want it, but eventually it looks like the bottom picture when you relog right?

**Comment by snarfaul** [comment]
That is correct.
Btw, it seem it will auto turn back to light even I didn't relog.

**Comment by Xruptor** [comment]
> That is correct.
> Btw, it seem it will auto turn back to light even I didn't relog.

Okay let me take a look then.  When was the last version that worked fine for you?

**Comment by Xruptor** [comment]
I think I was able to reproduce this.  What I will do it add a slider that will allow you to permanently set the transparency when the game loads.  That should fix your issue.

**Comment by Xruptor** [comment]
I've implemented the changes.  When you download the next version of xanChat.  You will find the new slider in the options panel.  You can type /xanchat.
