### ISSUE TITLE
Background over text.

### ISSUE THREAD

**Issue by Natlyz** [Xruptor/XanChat#13]
**Hello!**

I'm randomly getting this "bug", but no errors caught by Buggrabber :(

![WoWScrnShot_030920_140028](https://user-images.githubusercontent.com/60573947/76253702-368dd700-625c-11ea-893f-b887f8d30421.png)

Thanks for this addon :)

**Comment by Xruptor** [comment]
Hi! Can you please give me more information on the bug?  I can't tell from the picture what the issue is :)

**Comment by Natlyz** [comment]
Hello again! It's like the background of the "editbox" is over the text. Look how dull the colour of the text in the edit box looks when it should be the same colour as the channel text.

**Comment by Xruptor** [comment]
AH! Thanks I see it now.  The RGB charts help tremendously.  Huh, that's odd I don't know what could be causing that.  The background of the Editbox is set at a bottom level and shouldn't interfere with the text.  The only possibility I can think of is that the color settings restore portion of xanChat isn't restoring the colors properly 100% of the time.  So you get a variant of the color that is close but not close enough.  It could be a background on top of it but I highly doubt it.  I'll take a look at the background code as well.

You say this happens randomly?  Does this occur while you are playing the game?  Meaning that's it's fine for awhile and then suddenly it happens?  Or does this occur sometimes randomly when you login?

Finally has this started happening to you with the recent updates or after a certain version number?

**Comment by Natlyz** [comment]
I've notices it 2-3 times absolutely randomly when I was playing. So far I can only tell that "/reload ui" fixes the problem.

I need to test it more.

**Comment by Xruptor** [comment]
> I've noticed it 2-3 times absolutely randomly when I was playing. So far I can only tell that "/reload ui" fixes the problem.
> 
> I need to test it more.

Yeah that does seem really odd to me.  A reloadUI would just reapply the DB again and apply the textures.  Has this been a recent thing or within the last few updates?  Can you think of what version they may have started?

Let me know what you find out.  If you have a moment though don't forget to answer my questions above.  :)  That way I can go back into previous builds of xanChat.

**Comment by Natlyz** [comment]
> You say this happens randomly? 
Yes.

> Does this occur while you are playing the game?

Yes.

> Meaning that's it's fine for awhile and then suddenly it happens?

Yeah it can be fine and then I start tyoing and it's in dull colours. 

> Or does this occur sometimes randomly when you login?

Never notices it occur after log in. Usually midgame.

> Finally has this started happening to you with the recent updates or after a certain version number?

I'd say it started around after recent updates but I can't be sure.

**Comment by Natlyz** [comment]
Okay, so I found a way how you can replicate the "bug".

1. type /2 to enable typing in Trade channel;
2. take a flight path from A to B;

![434dgdfgd](https://user-images.githubusercontent.com/60573947/76346279-c9d71300-6315-11ea-91c5-8a5adf3603d2.png)

3. as soon as you see the message press Enter and you will get the "bug".

**Comment by Xruptor** [comment]
Interesting!  I wonder.... I know channels change color when you enter and leave them.  That could possibly be it.  Since you can't really use trade chat in point B.  (Well not that I recall LOL.)  BUT I'll see if I can reproduce this with your instructions.  TIME TO FLY BACK AND FORTH LIKE AN IMBECILE!

**Comment by Natlyz** [comment]
Maybe it's better to make the addon switch to "/say" if previously used (Trade in this case) channel is no longer available?

**Comment by Xruptor** [comment]
Okay I can confirm that it's working as intended.  It's what I figured.  When you leave a channel the color of the text changes to let you know that you aren't in the channel anymore.  This is a built in blizzard thing and really can't be changed.

I also can't forcefully change a channel when you leave one.  It causes taint issues in the chat frame which I try to avoid doing.

Just know when you leave a channel and the color changes, you aren't in that channel anymore.  This is intended and part of the core blizzard design.  There really isn't much I can do here.  So it's not technically a bug.

On a plus side I added an alternate editbox design you may like.  You can enable it in the next version :smile:

**Comment by Natlyz** [comment]
I hope I'll like it because I already like current edit box.

**Comment by Xruptor** [comment]
> I hope I'll like it because I already like current edit box.

Oh don't worry you can keep using the current one.  This is just an alternate style for the simplified edit box you can enable if you like.  It's optional.
