### ISSUE TITLE
Stylized names not working.

### ISSUE THREAD

**Issue by Natlyz** [Xruptor/XanChat#14]
**Hello!**

Looks like stylized names don't work for me. No matter how the name is spelled it's not coloured :(
 
![5454](https://user-images.githubusercontent.com/60573947/76254646-e3b51f00-625d-11ea-8a59-1e8f834bc989.png)

Thanks :)

**Comment by Xruptor** [comment]
The way it's currently coded it will not do stylize names in a sentence that has a player link already.  Player links are those that are clickable and have right click dropdowns.  Like the names with the 120 next to them in your picture.

It will only stylize names in certain system messages.  You can find the list in the filter list within the xanChat options.  It would be a coding nightmare to try to stylize the player link and the player name in the same sentence.  The reason I decided against this is simple.  What if the players name is 'Who'.  That means it would literally colorize every single time someone said the word 'Who' in the sentence.  This includes times they aren't even referring to the persons name.  That is why I restricted it to just system messages, like achievement alerts, party/raid notices, loot notices, etc...

I don't plan on changing this.  I'm truly sorry

**Comment by Natlyz** [comment]
Aha, thanks for explanation :) I thought maybe it was just not working.

**Comment by Xruptor** [comment]
> Aha, thanks for explanation :) I thought maybe it was just not working.

You are very welcome!
