### ISSUE TITLE
Sticky chat option.

### ISSUE THREAD

**Issue by Natlyz** [Xruptor/XanChat#15]
**Hello!**

I have a suggestion: an option to select which channels use sticky edit box.

e.g. I'm talking in a party chat. Party chat is set to sticky. Whispers aren't sticky. I reply to a guildie who whispered me by clicking on the name in chat, but can keep replying in party chat by pressing Enter without having to type /p after replying to a whisper.

Thanks!

**Comment by Xruptor** [comment]
I'll take a look at the code.  I can't recall but I remember something funny in the blizzard code regarding sticky channels and the Default Chat Frame.

**Comment by Natlyz** [comment]
Something funny?

**Comment by Xruptor** [comment]
As in something quirky or oddball about the sticky channels code.  I think there are restrictions.  But I cannot recall.  When I get home I'll take a look at it.

**Comment by Xruptor** [comment]
Alright so sticky channels are global.  They affect every chat frame.  However, its possible I suppose to select which chat types you want to make sticky or not.  I can look into it a bit more but I'm a bit tired.  I'll see it tomorrow morning.

**Comment by Xruptor** [comment]
Good morning!  So I took a look at the code and it's possible to do with a filter list.  Something similar to what I did with the stylized player names.  I will work on adding this filter list for sticky channels.  Afterwards though I'm going to stop making anymore feature enhancements to the xanChat.  I don't want the addon to end up like Prat or Chatter with too much bloated stuff.
