### ISSUE TITLE
Cosmetic suggestion.

### ISSUE THREAD

**Issue by Natlyz** [Xruptor/XanChat#16]
**Hello!** 

I want to suggest some minor adjustments to the alternative editbox.

![dsaasdc](https://user-images.githubusercontent.com/60573947/76685007-70c2f400-6621-11ea-893e-f7991fc8c8b2.png)

Thanks :)

**Comment by Xruptor** [comment]
The edge of the chat frame is actually just before the scrollbar.  The scrollbar acts as an independent object and has a vertical rectangle frame that holds it.  That is why the edit box stops just before the scrollbar.  In terms of the edit box height, I'm going to have to review the code.  I think there is a slight issue with edit box height and localization.  That may cause certain alphabets like Chinese or Korean and such to expand beyond the edit box background.  I cannot recall 100% but I will review it in the official blizzard code.  Positioning should be okay to do.  But need to check height stuff first.

**Comment by Natlyz** [comment]
I see, thanks! I'm not a programmer, is it possible to make the height of the edit box be dependant on localization?

**Comment by Xruptor** [comment]
> I see, thanks! I'm not a programmer, is it possible to make the height of the edit box dependant on localization?

It technically is possible to restrict it to a localized language.  Yet I would also have to see about custom fonts used for that language as well.  I'm doing some tests so far.  I experienced clipping with a few of the fonts but it's not a huge portion.  I'll have to test out a few others and see if I can reproduce it on other languages.  I also noticed a bug where the background textures for the tooltip border causes an overlapping situation if the editbox is set too small.  I believe it's a limitation of the texture set.  I'm still testing everything, I'll let you know what I find.

**Comment by Xruptor** [comment]
Okay so after some testing it seems that there are too many conflicts with fonts and sizes with the narrow editbox.  This even includes the disability options that Blizzard has for scaling and such, for folks with eyesight issues.  Font is also a problem as Custom UI's sometimes carry custom fonts for the Chat Box.  Just to say myself a lot of headache, I'm going to have to pass on making the editbox slimmer.  I'm sorry it's just too much of compatibility issue.

I can however move the editbox down a bit.  :smile:

**Comment by Xruptor** [comment]
Added it as an option in latest version.

**Comment by Natlyz** [comment]
Thanks! I'm going to test it today :)
