### ISSUE TITLE
Random copy malfunction. vol.2

### ISSUE THREAD

**Issue by Natlyz** [Xruptor/XanChat#19]
**Hello!**

I'm randomly experiencing this bug. Reload UI fixes it temporary.

![WoWScrnShot_040420_124155](https://user-images.githubusercontent.com/60573947/78456161-ba47b180-76aa-11ea-954c-54d9f68f4d13.png)

No error text, no nothing. Happens randomly. One time it's already been like that when I logged in.

Thanks :)

**Comment by Xruptor** [comment]
That's a weird bug.  Especially since I tell it to be a certain distance from the top.  It might be a redraw issue but this one is weird.  You say reload fixes it temporary?  While fixed what causes it to go back up to the top again?

Also what chat tab is that one?  A custom one or the main one?  Separate chat window? etc.. etc.

**Comment by Natlyz** [comment]
Reload fixes it but then it can occure again after relog or just randomly. So far I don't know what can be causing it.

That's a custom "Private" tab I made for whispers and raids/groups. But I think when I log in the bug can also occur while in the main tab.

I only use 1 chat window and switch tabs. 80% of time I'm in Private tab tho.

**Comment by Xruptor** [comment]
Okay I'll take a look.  Still a bit confused as to why it shows on top.  In the code I have it hard coded for -30 on the y-axis from the top.  So it should be -30 pixels down regardless.

If possible can you provide a fullscreen screenshot of your client?  You are more than welcome to blur out anything.  I just want to see a general idea of everything and your layout.  I think I have an idea of what is causing it, but I need to rule out some stuff.

**Comment by Natlyz** [comment]
You mean a screenshot of my UI or something else? Here's my UI :)

![WoWScrnShot_040620_180713](https://user-images.githubusercontent.com/60573947/78576658-a54b5980-7835-11ea-8e33-f2db1eded352.png)

**Comment by Xruptor** [comment]
> You mean a screenshot of my UI or something else? Here's my UI 😉
> 
> ![WoWScrnShot_040620_180713](https://user-images.githubusercontent.com/60573947/78576658-a54b5980-7835-11ea-8e33-f2db1eded352.png)

Okay cool so you have all the tabs docked?  I thought you had a separate chat window that you had customized?  It probably is a redraw problem but I'm trying to rule that out.  The size of the chatbox can't be it... but it's a possibility.

**Comment by Natlyz** [comment]
Everything is "docked", when I click on tabs it asks if I want to "undock".

**Comment by Xruptor** [comment]
> Everything is "docked", when I click on tabs it asks if I want to "undock".
> 
> I also have resized my chat a bit since you told me to do it when I had letters being cropped.

I think I found out what may be causing it.  But it should only happen rarely.  It has to do with a redraw issue when zoning and such.  Basically whenever you see a loading screen for something.

I'll see if I can find some weirdo way to trigger the bug to see if I can fix it.

**Comment by Natlyz** [comment]
I had the bug occur at least twice on log in: once in a capital, once in the outside world near Tal'Gurub in Zuldazar.

**Comment by Xruptor** [comment]
[xanChat.zip](https://github.com/Xruptor/XanChat/files/4446979/xanChat.zip)

Try this version and let me know if you still get it.

**Comment by Natlyz** [comment]
Sure, but it will take some time, considering that the bug occurs randomly and rarely.

**Comment by Natlyz** [comment]
Well, no bugs so far.

**Comment by Xruptor** [comment]
Have you still not experienced this bug again?  Let me know and I'll close this ticket.

**Comment by Natlyz** [comment]
I think you can close it.
