### ISSUE TITLE
Error&Suggestion

### ISSUE THREAD

**Issue by Natlyz** [Xruptor/XanChat#2]
Hello! I like your addon :)

Option suggestion: enable/disable textured borders for the edit box.

Also I'm getting this error:

> 2x XanChat\xanChat-6.0.lua:332: ChatFrame1:SetPoint(): Wrong object type for function
> [string "=[C]:"]: in function 'SetPoint'
> [string "@XanChat\xanChat-6.0.lua"]:332: in function <XanChat\xanChat.lua:302>
> [string "@XanChat\xanChat-6.0.lua"]:591: in function <XanChat\xanChat.lua:538>
> [string "=(tail call)"]: ?

**Comment by Xruptor** [comment]
Did you just start using xanChat or did you recently upgrade?

**Comment by Natlyz** [comment]
I've just started using it.

**Comment by Xruptor** [comment]
okay I'm going to try to reproduce this error.  If I can't, I may need your help.

**Comment by Xruptor** [comment]
Okay I found it and fixed it.  I also added the feature you wanted.

**Comment by Natlyz** [comment]
Thanks a lot! I couldn't even imagine it will get fixed so fast. I'll be able test it soon. And thanks for adding the feature :)
