### ISSUE TITLE
Chat timestamps

### ISSUE THREAD

**Issue by Infoblip** [Xruptor/XanChat#21]
Can we get an option for timestamps or did I miss that toggle?

**Comment by Xruptor** [comment]
Hello,
Actually timestamps have been implemented into WOW for some time now.  That's why the option was never added.

You can find the instructions in the description to the addon here:
https://www.wowinterface.com/downloads/info18787-xanChat.html


> Note: Timestamps were not included because Blizzard already implemented this feature into the client.
> Options -> Interface -> Social -> Chat Timestamps
