### ISSUE TITLE
Suggestions: Tints!

### ISSUE THREAD

**Issue by Natlyz** [Xruptor/XanChat#24]
**Hello!**

When having a lot of /w text (especially from several different people) my private chat turns into a wall of fuchsia text.

Would be nice to have incoming whispers to be of a slightly different colour (tint), or maybe an option to adjust incoming /w colour separately (with ColorPickerPlus addon).

![tintsuggest4324](https://user-images.githubusercontent.com/60573947/83339862-63d9a680-a2da-11ea-802b-895fa708df96.png)

I don't know any chat addons that can do that. Hope you'll like the idea.

**Thanks!**

**Comment by Xruptor** [comment]
So you want incoming whispers to be a different color?

**Comment by Natlyz** [comment]
I think the chat would look less as a wall of text when incoming /w's have a slightly different colour,

**Comment by Xruptor** [comment]
Well I suppose I can make just outgoing whispers a different color set by the player?

**Comment by Natlyz** [comment]
Yeah, that would be nice :)

**Comment by Xruptor** [comment]
Okay I'll add these changes. Please be advised once I add these two features, I will sadly no longer be adding anymore features to xanChat. Only bug fixes. I'm moving on from WOW and really don't want to focus on having to have an active subscription to add additional features. I'm truly sorry :(
