### ISSUE TITLE
Suggestion: Zone change!

### ISSUE THREAD

**Issue by Natlyz** [Xruptor/XanChat#25]
**Hello!**

Sometimes it can get really spammy when flying around herbing/mining between zones. 

![channelchange spam](https://user-images.githubusercontent.com/60573947/83340023-2a099f80-a2dc-11ea-81cb-69d869c6fd7a.png)

Would be nice to have an option to hide the zone (channel) change text 😊

**Thanks!**

**Comment by Xruptor** [comment]
Heyas! I'll take a look at this. I believe that text is added automatically to the chat by blizzard on zone change. I cannot recall if I have access to it or not. So it requires some testing.

**Comment by Xruptor** [comment]
Sorry for the delay have had quite a number of things come up. I can filter these zone messages out completely, if that is what you want.  Adding a Spam protection check is not exactly something I want to add. So just removing the text in general would be the simplest solution.

**Comment by Xruptor** [comment]
Okay I'll add these changes. Please be advised once I add these two features, I will sadly no longer be adding anymore features to xanChat. Only bug fixes. I'm moving on from WOW and really don't want to focus on having to have an active subscription to add additional features. I'm truly sorry :(

**Comment by Natlyz** [comment]
I see.. Hope they won't break this addon in Shadowlands :(

**Comment by Xruptor** [comment]
I hope so too. 😄   By moving on I mean I'm going to be unsubscribed for awhile. Not that I'm leaving the game entirely. I just don't have the urge or willpower right now to play. I may return in Shadowlands but not at the initial launch I think.
