### ISSUE TITLE
It's broken :(

### ISSUE THREAD

**Issue by Natlyz** [Xruptor/XanChat#27]
Hello! 

The addon is super broken on retail. Please help 😱

Thanks.

**Comment by Xruptor** [comment]
Hi! Good to hear from you. :)  Can you be more specific?  I don't have an active subscription, so I would have to see what errors you get.

**Comment by Natlyz** [comment]
It seems there are no errors related to XanChat, but nothing really works: no text outline, chat edit box doesn't use simplified texture, copybutton disappeared, the addon no longer allows me to scroll through the chat, and it no longer remembers what I typed before so I can't do Up Key + Enter to repeat my previous message, etc.

![WoWScrnShot_101420_223500](https://user-images.githubusercontent.com/60573947/96037246-4151bf80-0e6e-11eb-8a4b-723fb2ac0036.png)

**Comment by Natlyz** [comment]
_8x XanChat\config.lua:83: attempt to call method 'SetBackdrop' (a nil value)
[string "@XanChat\config.lua"]:83: in function <XanChat\config.lua:65>
[string "@XanChat\config.lua"]:668: in function <XanChat\config.lua:260>
[string "=(tail call)"]: ?_

**Comment by Natlyz** [comment]
8x XanChat\xanChat-8.2.lua:1492: attempt to call method 'EnableFilterList' (a nil value)
[string "@XanChat\xanChat-8.2.lua"]:1492: in function '?'
[string "@Alts\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...lts\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]:"]: ?
[string "@Alts\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...lts\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Alts\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function 'Fire'
[string "@Alts\Libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <...rface\Alts\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by mmau01** [comment]
Believe its due to changes mentioned here:
https://github.com/Stanzilla/WoWUIBugs/wiki/9.0.1-Consolidated-UI-Changes#backdrop-system-changes

**Comment by Xruptor** [comment]
I will be looking into this issue.  I'm going to assume as @mmau01 mentioned it's due to all the API changes Blizzard did.

I seriously don't understand why they constantly insist on changing the API and breaking addons especially when much of it is really unwarrented.  But that's just me just ranting because I'm forced to have to fix it LOL.  ;)

**Comment by Natlyz** [comment]
Can't wait to test it.

**Comment by Xruptor** [comment]
It will be awhile as I have quite a number of addons that are broken.  BagSync is taking priority right now but once things calm down I can focus on xanChat.  Blizzard really did a number on addon authors and killed a crap ton of functions and API calls.

**Comment by Xruptor** [comment]
I'm working on this now 😄 I was able to pinpoint a few of the errors.

**Comment by Natlyz** [comment]
Everything seems to be workign fine now. Thanks for a quick update 😊
