### ISSUE TITLE
9.1 is here...

### ISSUE THREAD

**Issue by Natlyz** [Xruptor/XanChat#30]
Hello! Got these errors with patch 9.1 😢

1x XanChat\xanChat-8.9.lua:1024: hooksecurefunc(): ToggleChatChannel is not a function
[string "=[C]:"]: in function 'hooksecurefunc'
[string "@XanChat\xanChat-8.9.lua"]:1024: in main chunk

1x XanChat\xanChat-8.9.lua:26: attempt to call method 'EnableAddon' (a nil value)
[string "@XanChat\xanChat-8.9.lua"]:26: in function <XanChat\xanChat.lua:15>

**Comment by Xruptor** [comment]
They must have changed ToggleChatChannel or removed it.

**Comment by Natlyz** [comment]
Thanks for a quick fix! 😊
