### ISSUE TITLE
Edit Mode taint?

### ISSUE THREAD

**Issue by Natlyz** [Xruptor/XanChat#32]
**Hello!**

I get this error when opening the Edit Mode:
```
1x [ADDON_ACTION_FORBIDDEN] AddOn 'XanChat' tried to call the protected function 'ClearTarget()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `ClearTarget'
[string "@Interface/FrameXML/EditModeManager.lua"]:1496: in function `ResetTargetAndFocus'
[string "@Interface/FrameXML/EditModeManager.lua"]:1531: in function `RefreshTargetAndFocus'
[string "@Interface/FrameXML/EditModeManager.lua"]:1462: in function `OnEditModeEnter'
[string "@Interface/FrameXML/EditModeManager.lua"]:171: in function `EnterEditMode'
[string "@Interface/FrameXML/EditModeManager.lua"]:193: in function <Interface/FrameXML/EditModeManager.lua:191>
[string "=[C]"]: in function `Show'
[string "@Interface/FrameXML/UIParent.lua"]:2844: in function `SetUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2648: in function `ShowUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2552: in function <Interface/FrameXML/UIParent.lua:2548>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3150: in function `ShowUIPanel'
[string "@Interface/FrameXML/FloatingChatFrame.lua"]:282: in function `func'
[string "@Interface/SharedXML/UIDropDownMenu.lua"]:1007: in function `UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1>
```

**Thanks! 🥞**

**Comment by Xruptor** [comment]
I took the liberty of looking this up.  It appears that there are severe taint issues with the new Edit Mode ability.  A lot of addons trigger it for the tiniest thing.  Apparently its a known issue at Blizzard and they have time to fix it before launch.  Case in point, XanChat doesn't even use the ClearTarget() function.  However its being blamed for it and triggering the taint error.

Example thread:
https://www.wowinterface.com/forums/showthread.php?t=59244

There are several reports filed here too:
https://github.com/Stanzilla/WoWUIBugs/issues/

https://github.com/Stanzilla/WoWUIBugs/issues/256

I'll see what I can do to minimize it.  But they seem to be having major issues with that before launch.  So not sure if I should invest time into it.  Regardless, I can at least try to see what may be triggering it.  Watch it be some stupid variable or something.

**Comment by Natlyz** [comment]
Thanks!

Yeah, from what I know the Blizzard UI is more broken than ever right now. Hopefully they will fix it before the actual release.

**Comment by Natlyz** [comment]
Btw, outside the Edit Mode I have no problems with XanChat so far 😊

**Comment by Xruptor** [comment]
I created a temporary workaround for the time being.

**Comment by Natlyz** [comment]
Thanks! can't wait to test it.

**Comment by Xruptor** [comment]
I have another ticket stating there are taint issues with xanChat.  Which is  #37 

Are you getting taint issues with xanChat?  I cannot seem to reproduce this problem and I've not seen anymore taint issues with xanChat since I implemented the changes.
