### ISSUE TITLE
 chat text outline and shadow

### ISSUE THREAD

**Issue by tanrak** [Xruptor/XanChat#34]
XanChat offers a shadow option. But this is actually "THINOUTLINE" without shadow. I investigate the XanChat.lua and in line [1658](https://github.com/Xruptor/XanChat/blob/6a6133e9d253d41636c033c597ec98ef3f627ede/XanChat.lua#L1658) i found the reason for that. Since I use the standardized "THINOUTLINE" with shadow for all my text frames i have commented out this line.

Now it would be nice if there was maybe the possibility to set this in the options. Maybe in this form:

- [ ] "Add outline to the chat text font."
  - [ ] "... and shadow to the chat text font.

By the way, thanks for updating all your addons. I use some of them.

**Comment by Xruptor** [comment]
You are very welcome :)  I'm glad you enjoy my addons.

So you are saying that the THINOUTLINE is actually not the shadow and by commenting it out it gives the shadow?  I'll need to see if that's the case to add additional options if necessary.

**Comment by tanrak** [comment]
Enclosed are two pictures with a hopefully understandable explanation...

Imho the default THINOUTLINE is an text outline with shadow (image1):
https://github.com/Xruptor/XanChat/blob/6a6133e9d253d41636c033c597ec98ef3f627ede/XanChat.lua#L1657

Because the alpha value in the additional code line 1658 was set to 0, it ist now only an outline text without shadow (image2):
https://github.com/Xruptor/XanChat/blob/6a6133e9d253d41636c033c597ec98ef3f627ede/XanChat.lua#L1658

![outline_with_shadow](https://user-images.githubusercontent.com/35105392/201118167-dbc6c0a4-89ce-4fc0-a4b3-6e3b880edb6b.jpg)
![outline_without_shadow](https://user-images.githubusercontent.com/35105392/201118184-6e071f71-91c9-4f3f-a6e7-c2800ce28a67.jpg)

I know the difference is not big, but especially with a light background I find the variant with shadow more readable.

**Comment by Xruptor** [comment]
Oh I see what you mean now.  Yes the alpha layer for the secondary shadow was removed with that option.  That is why it's showing like that depending on the alpha level you have on the chat.  I'll make an additional option to separate it then.  That should help out a bit.
