### ISSUE TITLE
Transparancy

### ISSUE THREAD

**Issue by Huntid** [Xruptor/XanChat#36]
Even after the latest update, I still cannot get the background to go fully transparent/fade away when its not being hovered over or used.

**Comment by Xruptor** [comment]
I will take a look when I can.  There is a few bugs I had to work around until the 10.0.2 patch.  So it could be part of that.

**Comment by Huntid** [comment]
I believe it ended up being a setting in the options of the addon. It
appears to be working now for me. thank you for all that you do.. :)
