### ISSUE TITLE
XanChat and Edit Mode

### ISSUE THREAD

**Issue by Spiderkeg** [Xruptor/XanChat#37]
I'm sure this has been discussed before, but still wanted to chime in with my experiences.

With XanChat the only addon loaded, Edit Mode is tainted.  This has already been noted.

What I am seeing is when other addons are loaded, Bartender4 as a prime example, XanChat is tainting Bartender4 to also be blocked from Edit Mode.

Should be noted that Bartender4, by itself, does not normally taint Edit Mode.  I've noticed this also the case with Bazooka, various Pet addons, etc.  None of these normally taint Edit Mode, at least not in a fresh /reload but when XanChat is also loaded all of these addons will be included in the taint.

I get no specific error messages, but no taint occurs when XanChat is removed, so no idea what the issue is but something with the addon is clearly causing something to happen.

**Comment by Xruptor** [comment]
I'm not able to get these Taint modes errors on my end.  I'll try loading Bartender myself and see if that causes it.  I had originally fixed the taint issues on another ticket.  To be fair, the new Blizzard Edit Mode is VERY buggy and lots of addons taint it.  If you can provide the exact taint error that would be great.

**Comment by Xruptor** [comment]
Also make sure you are using the latest version of xanChat 9.7

**Comment by Xruptor** [comment]
Let me know if the issue still happens with the latest version and with on xanChat loaded.
