### ISSUE TITLE
"Hide the EditBox Border" does not seem to work properly

### ISSUE THREAD

**Issue by tanrak** [Xruptor/XanChat#38]
There is no difference whether I turn the option "Hide the EditBox Border" on or off. In both cases, no border is visible.

**Comment by Xruptor** [comment]
Hmm that's odd it should be working.  Classic, WOTLK or Retail?

**Comment by tanrak** [comment]
Hi, i play WOTLK. It does not work there. I then also tested it in Retail where it works correctly.

**Comment by Xruptor** [comment]
> Hi, i play WOTLK. It does not work there. I then also tested it in Retail where it works correctly.

Okay so it works fine on Retail but not on WOTLK.  I'll take a look.

**Comment by Xruptor** [comment]
I just logged in to my WOTLK account and was able to successfully hide the EditBox border with "Hide the Editbox Border".  Please note you cannot have this option enabled with "Simplified EditBox" or "Alternative EditBox".  Selecting "Hide the EditBox Border" will automatically disable the other two options.  Selecting any of the "Simplified" or "Alternative" options will disable the "Hide the Editbox Border" option.  It's not possible to have a simplified border AND hide it at the same time.

Please make sure to check these options and ensure they are correct.  It's working perfectly fine on my end but if you still have the problem, it could be something else I'm missing or a conflict with another addon.

**Comment by Xruptor** [comment]
![image](https://user-images.githubusercontent.com/202515/204091940-3faf6174-6cd6-46b0-a1ed-58b035011708.png)

**Comment by tanrak** [comment]
Yes "Hide the Editbox Border" works. The Border is gone. But if i uncheck the option than the default Border should be visible. But it is not. No matter if I turn the option on or off, the Border is not visible.

**Comment by Xruptor** [comment]
I will try this again on my WOTLK account.  But if I recall when I used the option, the border was shown and hidden when I toggled the option.
