### ISSUE TITLE
Short names

### ISSUE THREAD

**Issue by tanrak** [Xruptor/XanChat#39]
I would like to use the short names. But these only work with the English language. I see that the addon is prepared for different languages. So I tried and i created and edited a file locale\deDE.lua and also make a entry in the toc file. But apparently it does not load it. Did I miss something?
Edit: I have also changed the line 3 in deDE.lua to `local L = LibStub("AceLocale-3.0"):NewLocale(ADDON_NAME, "deDE", true)`

**Comment by Xruptor** [comment]
It needs to be declared in the TOC file.  If you can provide me with the changes, I can apply them and upload them for the newest versions.  Please review enUS.lua locale file found under xanChat.

**Comment by Xruptor** [comment]
local L = LibStub("AceLocale-3.0"):NewLocale(ADDON_NAME, "deDE")

Then just translate all the english text to deDE.

**Comment by tanrak** [comment]
Without `, true` in the code line it works now. I will translate to german something in the next few days.

**Comment by tanrak** [comment]
I noticed two things while translating.
1. The labeling in the settings menu for hiding various buttons is a bit messed up in my opinion. The button with the speech bubble is the "Chat menu" and the button with the megaphone is the button for the "Chat channels". I have attached an Image with labels (red incorrect and black correct)
2. The Chat menu button also exists in wrath classic (and imho also in classic) but the option for hide it is missing in wrath.

**Comment by Xruptor** [comment]
Okay I will rename them.

**Comment by tanrak** [comment]
Translation done: https://gist.github.com/tanrak/bb19bcc325123e58255d3699b8b7e1ab

And also please check the number two in the previous comment from me.

**Comment by Xruptor** [comment]
> Translation done: https://gist.github.com/tanrak/bb19bcc325123e58255d3699b8b7e1ab
> 
> And also please check the number two in the previous comment from me.

Thank you very much!  I will definitely make those changes that you said above don't worry.
