### ISSUE TITLE
Bugged Achievement messages with Alts addon.

### ISSUE THREAD

**Issue by Natlyz** [Xruptor/XanChat#4]
Hello!

I want to report a bug.

![WoWScrnShot_020320_170056](https://user-images.githubusercontent.com/60573947/73683873-22424180-46d4-11ea-88dc-3b2c80690117.png)

Not sure if it's yours addon causing it or the Alts addon. I noticed that for some reason Achievment messages are displayed differently from usual messages and that one of the ( ) is coloured yellow there and the name in ( ) is positioned after text. 

Also not sure why but item and class colours don't work for BNET messages.

Hope that helps. Thanks!

**Comment by Xruptor** [comment]
This is not a bug with xanChat.  xanChat doesn't replace  anything in chat other than the channel names, which are handled differently.  It looks like the alt addon is attaching text at the end of the achievement message, but the author forgot to close the color tags.  So the Achievement gold/yellow color tag is bleeding into the alt name.  You may want to alert the author.

**Comment by Natlyz** [comment]
Thanks! Yeah, I'm alerting the author of Alts.. wasn't sure which addon was causing it.
