### ISSUE TITLE
Unclickable item links and links in the Newcomer channel.

### ISSUE THREAD

**Issue by Natlyz** [Xruptor/XanChat#41]
**Hello!** 

I noticed that item links in the chat sometimes can't be clicked on. No errors caught.

Also internet links don't work in the /4 channel for newcomers. They just appear as plain text, not as links in [...].

**Thanks!**

**Comment by Xruptor** [comment]
Need some examples of items that don't work when you link them.

I think the newcomers channel is protected and cannot be pushed with links if I'm not mistaken.  I'd have to look.

**Comment by Natlyz** [comment]
Stangely I can't reproduce this bug today, but it happened several times before I finally decided to report it. I will give more details the next time it occurs again.

**Comment by Xruptor** [comment]
> Stangely I can't reproduce this bug today, but it happened several times before I finally decided to report it. I will give more details the next time it occurs again.

It's possible that another addon caused an error that preventing tooltips from displaying.  The tooltip used in the chat window is called ItemRefTooltip.  It's also possible that xanChat created an error and prevented the tooltips from being clickable.  Unless you have a bug addon installed, it may have been hidden or surpressed.  I use BugSack + BugGrabber myself.  Happy Holidays!!! 🎄 

https://www.curseforge.com/wow/addons/bugsack
https://www.curseforge.com/wow/addons/bug-grabber

**Comment by Natlyz** [comment]
Yeah, I have bugsack and grabber. No errors caught.

Happy Holidays! 😊

**Comment by Natlyz** [comment]
I noticed that the bug happens mostly after I've tabbed out of the game. Reload doesn't fix it, but relog does. One time when the links in chat became inactive I started clicking on the chat and links repeatedly.. and it suddenly fixed itself and the link opened. What is happening? Is my game client haunted? 😱

**Comment by Xruptor** [comment]
> I noticed that the bug happens mostly after I tab out of the game. Reload doesn't fix it, but relog does. One time when item links in chat became inactive I started clicking on the chat window and links repeatedly.. and it suddenly fixed itself and the link opened. What is happening? Is my game client haunted? 😱

Something else may possibly be going on outside the scope of xanChat.  If a reload doesn't fix it and only a relog does then it may be something else in the client.  When you do a reload() it basically rereads and interprets all the Addon data again.  It's like doing a complete refresh in the memory for the addons.  So it would be loading as new.  If even doing that doesn't fix the issue then there is possibly something else affecting the problem.  You also claim that clicking multiple times eventually does magically fix the issue.  If there are no errors generated and this just magically seems to work after repeated clicks I can only assume one of three possibilities.  1) That xanChat is indeed broken and is causing the issue.  2) Your client may be having some sort of conflict with another addon in regards to the chat window. 3) There is some sort of weirdo file corruption going on with your client.

With 1) the simplest solution would be to disable xanChat and see if you can replicate the error somewhow.  If the issue still occurs then it's not xanChat.  With issue 2) that would require to disable all addons and see if the problem still persists.  In terms of 3) that would require some sort of file cleanup or repair process on the Blizzard launcher.

I don't think your game client is haunted, but something obviously is broken.  I want to point out that I don't have the issues you are referring to on my end.  So not entirely 100% sure it's xanChat related, but it could be.

**Comment by Xruptor** [comment]
I never heard back.  So I'm just going to close the ticket.

**Comment by Natlyz** [comment]
> I never heard back. So I'm just going to close the ticket.

FarmHud is blocking chat and inventory, making most of it unsuable.

**Comment by Xruptor** [comment]
> FarmHud

Ah thanks for the response!  That is good to know.  Glad you were able to sort it out!
