### ISSUE TITLE
Copy bug.

### ISSUE THREAD

**Issue by Natlyz** [Xruptor/XanChat#42]
**Hello!**

With the new patch the copy button is clipping with the default button. No errors caught.

![WoWScrnShot_012723_205051](https://user-images.githubusercontent.com/60573947/215168452-a1dbcab8-2506-46b7-8c14-85b326d5b2bb.png)

**Thanks 😊**

**Comment by Xruptor** [comment]
Odd it works perfectly fine for me on the Retail servers.  Do you hide the scroll bars by any chance?  Can you take a screenshot of your settings for me when you can.

**Comment by Natlyz** [comment]
![scr3456](https://user-images.githubusercontent.com/60573947/215193479-6da889c6-0976-4b97-b171-7ca4d453cc22.png)

**Comment by Natlyz** [comment]
Fixed with the recent update! Thanks 😉

**Comment by Xruptor** [comment]
Oh okay I could have sworn I fixed that XD.  The most recent one right?

**Comment by Natlyz** [comment]
> Oh okay I could have sworn I fixed that XD. The most recent one right? It must not have completely gone through CurseForge or something.

Yeah, the most recent update from curse, Thanks for the quick fix 😁
