### ISSUE TITLE
Side bar and minimize button visible in 10.4 with hidden options enabled

### ISSUE THREAD

**Issue by ronin-seven** [Xruptor/XanChat#43]
The side bar is visible on my main/tabbed chat window and the minimize button is visible on my 2nd chat window, outlined in red:
![image](https://user-images.githubusercontent.com/47235915/215254364-1084c174-2013-4c6f-bd16-de6179a75ec2.png)

My configuration:
![image](https://user-images.githubusercontent.com/47235915/215254417-7d7fb9e3-fa6d-49ca-a447-c0ea6613cc6e.png)

I've reverted to 10.3 for the time being.

**Comment by Xruptor** [comment]
Is this on Retail, Classic, or WOTLK?

**Comment by Xruptor** [comment]
Okay never mind I see what it is.  Blizzard recently changed a few things on the chat windows and I had to update the addon to compensate for it.  Part of the changes was how the ScrollBar and ButtonBar frame is handled.  I believe it's part of their Edit Mode cleanup.  Regardless, I added an additional **NEW** option to hide the left and side Button Bars.  That should do exactly what you want.  :)
