### ISSUE TITLE
[Feature request] Keep the chat menu button & chat channel/voice button across all chat windows + [Bug] scoll button stays even when at bottom of chat window.

### ISSUE THREAD

**Issue by JBabbb** [Xruptor/XanChat#44]
Hello,

Just downloaded this addon, and it is incredible. I noticed two things immediately after fiddling with it.

1. Feature request - Would you consider adding an option for the chat menu + chat channel/voice buttons to stay appearing on all chat windows (not just general)?
2.  Bug - Once I use the chat scroll feature, even when scrolling to the bottom, it does not disappear as it should & stays appearing in the chat box (until reloading UI)

Thank you :)

**Comment by Xruptor** [comment]
> Bug - Once I use the chat scroll feature, even when scrolling to the bottom, it does not disappear as it should & stays appearing in the chat box (until reloading UI)

Can you show me a picture of what you mean?  I'm not understanding what the issue is.  Sometimes a picture is worth a thousand words lol.

> Feature request - Would you consider adding an option for the chat menu + chat channel/voice buttons to stay appearing on all chat windows (not just general)?

Sadly there are built in limitations that prevent massive tampering of the chat windows anymore in the game.  Primarily since they introduce the Edit Mode option for the UI in Retail.  Tampering with the Chat windows opens up a lot of "Taint" error and issues.  Otherwise I'd be happy to implement it.

**Comment by JBabbb** [comment]
Understood, I did do a re-install of the addon and it seems to have fixed it, the blue circle shows what I was referring to [https://imgur.com/a/kfuPpIV](url)

Also, I found something else after playing hardcore classic & comparing the UI's. I like to hide the chat tabs (circled in red), but if you 'disable background fade on chat frames', it makes the chat tabs stay appearing even if 'hide tab chats' is selected.

Hope this makes more sense, I suck at all this stuff - I just miss the old UI lol :(

**Comment by Xruptor** [comment]
Hmmm I'll have to take a look at that.  It shouldn't be doing that and it may be the modifications to the UI they made causing the problem again.  They really did lock down a lot of the frames for their Edit Mode.  It's one big mess....
