### ISSUE TITLE
Suggestion: Clear copy chat buffer

### ISSUE THREAD

**Issue by nancikennedy** [Xruptor/XanChat#45]
It would be beneficial to have a slash command to clear the currently saved chat buffer so that if you're outputting a large volume of text to chat for copying purposes, you could issue the clear command before that.

**Comment by Xruptor** [comment]
That's actually not a bad idea! I'll have to see about implementing it :)

**Comment by nancikennedy** [comment]
It's a neat idea, just wouldn't work for me.

For me, I use ReHack to run a lua script that outputs to chat all the code necessary to replicate the currently logged in chars actionbars. I then copy that output into another page in ReHack that is used as the source for the class/spec when running another page script that does a fresh reset of all a char's action bars. Being able to include in the script a precall to clear the chat means that the only thing in the chat woudl be the code output I need to copy to make it all work.  Since the output is never going to be the same number of lines across class/specs, a slider option wouldn't work for me.

Thanks for the attention
