### ISSUE TITLE
Since patch I cannot change tab anymore.

### ISSUE THREAD

**Issue by cgsub** [Xruptor/XanChat#46]
Since the latest patch (10.2.6) I'm stuck on the general tab nothing happen when I click other tabs

I m running English Retail version of the game and latest curseforge version of the addon (XanChat-v10.7.zip 9/18/2023)

**Comment by Xruptor** [comment]
Hmmm that's odd.  Perhaps they changed something in the chat API....... again.  *facepalm*
I'd have to take a look.

**Comment by cgsub** [comment]
I noticed that for some reason blizzard seems to have enforced the activation of channel 5 (services) on every tab. 
It seem to randomly reset for some reason, just had that happening without XanChat enabled. just so you know...

**Comment by Xruptor** [comment]
Okay sorry for delay, but I just logged in today on a trial account and I was able to move around in the chat tabs on the live servers.  Can you explain to me at least in detail or in pictures the issue?  I'm currently updating all my addons for upcoming cataclysm classic and want to squash as many bugs as possible.  Any pictures you can provide do help!

**Comment by cgsub** [comment]
It's probably not related to your addon, that is what U meant with my latest message, 
I guess I should have closed the issue, I'm not very used with github, I'm barely using it.

This is related with the latest changes, it's also happening without your addon.
