### ISSUE TITLE
Dungeon finder error

### ISSUE THREAD

**Issue by Natlyz** [Xruptor/XanChat#47]
**Hello!** 

Not sure if it's a XanChat bug or some other bug but XanChat is definitely mentioned in this error:

```
24x [ADDON_ACTION_BLOCKED] AddOn 'XanChat' tried to call the protected function 'GetPlaystyleString()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `GetPlaystyleString'
[string "@Blizzard_GroupFinder/Mainline/LFGList.lua"]:4054: in function <...aceBlizzard_GroupFinder/Mainline/LFGList.lua:4043>
[string "=[C]"]: in function `LFGListUtil_SetSearchEntryTooltip'
[string "@Blizzard_GroupFinder/Mainline/LFGList.lua"]:2887: in function <...aceBlizzard_GroupFinder/Mainline/LFGList.lua:2884>
[string "=[C]"]: ?

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}
```
This error usually pops up when using the dungeon finder's custom groups.

**Thanks 😀**

**Comment by Xruptor** [comment]
Okay so xanChat does not use the **"GetPlaystyleString"** function at all.  Which means it's being blamed for the error.  According to your error report BugGrabber is reporting the previous as line 4054 in Blizzards own GroupFinder addon and specifically in **LFGList.lua**.  Which means it's a bug on their end.  You may want to report it using a the bug report tool.


[string "=[C]"]: in function `GetPlaystyleString'
[string "@**Blizzard_GroupFinder/**Mainline/**LFGList.lua**"]:**4054**: in function <...ace**Blizzard_GroupFinder/Mainline/LFGList.lua:4043**>

**Comment by Natlyz** [comment]
Thanks! Reported to Blizzard using the in-game bug report.

**Comment by Xruptor** [comment]
> Thanks! Reported to Blizzard using the in-game bug report.

Of course! Any time :)  If you still think it's an addon triggering it, you can always disable xanChat and see what other addon gets blamed.  The best solution though would to use a document search software to find any addon you have installed that has the string  **GetPlaystyleString**.  I usually recommend https://www.mythicsoft.com/agentransack/  agent ransack for this.  Just set the directory to your mods folder and put GetPlaystyleString in the field called "Containing text".  Make sure subfolders is checked then just press "start".
