### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by wheatbread** [Xruptor/XanChat#5]
Hello!

I just installed Xanchat v6.2 and started getting the following error spam:

`959x XanChat\xanChat-6.2.lua:295: attempt to index local 'relativeTo' (a nil value)
[string "@XanChat\xanChat-6.2.lua"]:295: in function <XanChat\xanChat.lua:279>
[string "@XanChat\xanChat-6.2.lua"]:627: in function <XanChat\xanChat.lua:626>
[string "=[C]"]: in function `StopMovingOrSizing'
[string "@FrameXML\FloatingChatFrame.lua"]:1277: in function `FCF_StopDragging'
[string "@FrameXML\FloatingChatFrame.lua"]:1323: in function `FCFTab_OnDragStop'
[string "@FrameXML\FloatingChatFrame.lua"]:1314: in function <FrameXML\FloatingChatFrame.lua:1296>

Locals:
chatFrame = ChatFrame1 {
 GatherSelectedText = <function> defined =[C]:-1
 RefreshIfNecessary = <function> defined =[C]:-1
 OnPostShow = <function> defined =[C]:-1
 CalculateLineAlphaValueFromTimestamp = <function> defined =[C]:-1
 ScrollUp = <function> defined =[C]:-1
 tellTimer = 300380.609000
 fadeDurationSecs = 3
 StopMovingOrSizing = <function> defined =[C]:-1
 GetFading = <function> defined =[C]:-1
 IsTextCopyable = <function> defined =[C]:-1
 shouldFadeAfterInactivity = true
 SetIndentedWordWrap = <function> defined =[C]:-1
 GetJustifyV = <function> defined =[C]:-1
 ScrollToBottom = <function> defined =[C]:-1
 GetMaxLines = <function> defined =[C]:-1
 GetIndentedWordWrap = <function> defined =[C]:-1
 buttonSide = "left"
 GetFont = <function> defined =[C]:-1
 checkedGMOTD = true
 SetMaxLines = <function> defined =[C]:-1
 CalculateSelectingCharacterIndicesForVisibleLine = <function> defined =[C]:-1
 OnPostUpdate = <function> defined =[C]:-1
 RefreshDisplay = <function> defined =[C]:-1
 SetFontObject = <function> defined =[C]:-1
 textIsCopyable = false
 SetOnScrollChangedCallback = <function> defined =[C]:-1
 CalculateNumVisibleLines = <function> defined =[C]:-1
 overrideFadeTimestamp = 300138.405000
 MarkDisplayDirty = <function> defined =[C]:-1
 GetMessageInfo = <function> defined =[C]:-1
 GetOnScrollChangedCallback = <function> defined =[C]:-1
 AtTop = <function> defined =[C]:-1
 GetFontObject = <function> defined =[C]:-1
 fontStringPool = <table> {
 }
 CanEffectivelyFade = <function> defined =[C]:-1
 OnPreSizeChanged = <function> defined =[C]:-1
 GetScrollOffset = <function> defined =[C]:-1
 GetSpacing = <function> defined =[C]:-1
 OnPreLoad = <function> defined =[C]:-1
 SetSpacing = <function> defined =[C]:-1
 name = "Gen"
 CalculateLineSpacing = <function> defined =[C]:-1
 AddMessage = <function> defined @XanChat\xanChat.lua:248
 InitializeFontableFrame = <function> defined =[C]:-1
 GetShadowColor = <function> defined =[C]:-1
 isUninteractable = false
 SetOnTextCopiedCallback = <function> defined =[C]:-1
 mouseOutTime = 0
 RemoveMessagesByPredicate = <function> defined =[C]:-1
 TransformMessages = <function> defined =[C]:-1
 SetShadowColor = <function> defined =[C]:-1
 buttonFrame = ChatFrame1ButtonFrame {
 }
 HasFontObject = <function> defined =[C]:-1
 isDocked = 1
 GetOnTextCopiedCallback = <function> defined =[C]:-1
 SetFading = <function> defined =[C]:-1
 OnPostHide = <function> defined =[C]:-1
 alternativeDefaultLanguage = "Common"
 isInitialized = 1
 GetNumVisibleLines = <function> defined =[C]:-1
 GetInsertMode = <function> defined =[C]:-1
 SetTimeVisible = <function> defined =[C]:-1
 hasOwnFontObject = true
 Clear = <function> defined =[C]:-1
 oldAlpha = 0.858824
 channelList = <table> {
 }
 GetTimeVisible = <function> defined =[C]:-1
 IsSelectingText = <function> defined =[C]:-1
 SetTextCopyable = <function> defined =[C]:-1
 BackFillMessage = <function> defined =[C]:-1
 UnpackageEntry = <function> defined =[C]:-1
 FontStringContainer = <unnamed> {
 }
 SetShadowOffset = <function> defined =[C]:-1
 messageTypeList = <table> {
 }
 timeVisibleSecs = 120
 PackageEntry = <function> defined =[C]:-1
 MakeFontObjectCustom = <function> defined =[C]:-1
 fontObject = table: 00000226230C66C0 {
 }
 SetInsertMode = <function> defined =[C]:-1
 mouseInTime = 0
 UpdateSelectingText = <function> defined =[C]:-1
 zoneChannelList = <table> {
 }
 SetScrollOffset = <function> defined =[C]:-1
 onDisplayRefreshedCallback = <function> defined =[C]:-1
 insertMode = 2
 ResetSelectingText = <function> defined =[C]:-1
 hasBeenFaded = true
 0 = <userdata>
 GetTextColor = <function> defined =[C]:-1
 ScrollBar = <unnamed> {
 }
 CallOnDisplayRefreshed = <function> defined =[C]:-1
 OnFontObjectUpdated = <function> defined =[C]:-1
 ResizeButton = ChatFrame1ResizeButton {
 }
 onScrollChangedCallback = <function> defined =[C]:-1
 MarkLayoutDirty = <function> defined =[C]:-1
 SetFont = <function> defined =[C]:-1
 OnPostMouseDown = <function> defined =[C]:-1
 defaultLanguage = "Common"
 isLayoutDirty = false
 ScrollToTop = `

**Comment by Xruptor** [comment]
That's odd you shouldn't be getting that error.  The frames should have a relative position.  But I'll fix it right away.  I'll just add a check for it.  Thanks for filing the error report!

**Comment by wheatbread** [comment]
Thank you!
