### ISSUE TITLE
Links not clickable?

### ISSUE THREAD

**Issue by wheatbread** [Xruptor/XanChat#7]
Hello! 

The addon description says, "Has built in URL support. Clickable URL links in the chat window."  However, I cannot for the life of me figure out how to make URL links work.  Holding any sort of modifier + left/ right clicking, or no modifier while clicking does not work. 

The URL link appears like this in chat: https://imgur.com/zJz927n    Clicking on the blue clickable part doesn't do anything. :(

It seems to be having https:// that somehow messes up the link.  Others that don't have it seem to work fine.

**Comment by Xruptor** [comment]
This seems like a bug to me.  I will look into this.  Odd I don't remember having this issue myself.  But it's good that you provided an image.

![image](https://user-images.githubusercontent.com/202515/74889978-a3463d80-5350-11ea-9946-334898d3dc3d.png)

**Comment by Xruptor** [comment]
Can you tell me the list of addons you have installed?  Also please provide me with the link you used that generated the error.  (I'm assuming it's,  https://www.reddit.com/r/CompetitiveWoW/comments/f6i2ih/5_mask_full_clear_sw_vod_assassination_rogue/)

**Comment by wheatbread** [comment]
Oh, I didn't realize it was a conflict with another addon causing it!  After you said that, I went to test disabling addons one by one, and pinpointed which one it was:  https://www.curseforge.com/wow/addons/chat-copy-paste

So all links that have https:// in them turn into that shown in the picture when both xanchat and chat copy paste are enabled.

**Comment by Xruptor** [comment]
> Oh, I didn't realize it was a conflict with another addon causing it! After you said that, I went to test disabling addons one by one, and pinpointed which one it was: https://www.curseforge.com/wow/addons/chat-copy-paste
> 
> So all links that have https:// in them turn into that shown in the picture when both xanchat and chat copy paste are enabled.

I'll take a look at that link.  But if it's conflicting you may want to disable it.  I'm not entirely sure what it does but I'll review it.

**Comment by Xruptor** [comment]
After reviewing the addon, yes it does conflict with xanChat.  It filters URL links after they have been already filtered by xanChat.  I use Blizzards built in filtering to accomplish this.  It then goes to chat where Chat-Copy-Paste modifies it again with a new link called ccpCustomLink.  That's why you see it in the image above.

Aside from being able to copy and paste the chat, all other functionality is in xanChat.  Is the copy and paste function something you use often?

**Comment by wheatbread** [comment]
Thank you for taking a look!

Oh, yes, it's quite useful when wanting to, say, repeat verbatim what someone said (for example, copying someone's guild spam to show a friend who's looking for one, or copying someone's trade spam to note down their prices, or even to just show a friend what crazy thing someone said in this dungeon, etc.).  I don't know how much work it entails to add copy chat to the addon, but if it's not too much it would be wonderful to have it built in.

**Comment by Natlyz** [comment]
I also use copy and paste function often to copy what NPCs or certain people said.

**Comment by Xruptor** [comment]
> I also use copy and paste function often to copy what NPCs or certain people said.

Okay I added this feature.  But I did not make the window that opens up to copy and paste movable.  I think it's pointless since you will be closing it after you copy anyways.  It will always show at the center of your screen.  But other than that it works pretty much the same.

**Comment by Xruptor** [comment]
It will be released in next update. I'm working on another feature request as well.

**Comment by Xruptor** [comment]
Just an update.  I'll be releasing this soon once I can get #6 complete.

**Comment by wheatbread** [comment]
Amazing, thanks so much!

**Comment by Natlyz** [comment]
I really like the new copy feature.
