### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by Natlyz** [Xruptor/XanChat#8]
Hello!

I've randomly encountered this error today. 

_2x XanChat\xanChat-6.7.lua:190: attempt to index local 'player' (a nil value)
[string "@XanChat\xanChat-6.7.lua"]:190: in function 'parsePlayerInfo'
[string "@XanChat\xanChat-6.7.lua"]:491: in function 'AddMessage'
[string "@FrameXML\ChatFrame.lua"]:3651: in function 'ChatFrame_MessageEventHandler'
[string "@FrameXML\ChatFrame.lua"]:3018: in function 'ChatFrame_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>_

I'm using the latest version from curse.com.

Thanks :)

**Comment by Xruptor** [comment]
Well that's really odd.  The only way to get even to that function is passing all my other checks. The variable 'player' shouldn't be nil.  Huh.... let me check out the code.
